In [1]:
import numpy as np
import numpy.random as rn
import numpy.linalg as la

In [11]:
def GS(A, tol = 10**(-12)) :
    m, n =A.shape
    Idx = list()
    Q = np.matrix(np.zeros((m, n))) #zero matrix setting
    Q[:, 0] = A[:, 0]/la.norm(A[:, 0])

    for i in range(1, n) :      #Formula of Gram Schmdit
        Q[:, i] = A[:, i].copy()
        for j in range(i) :
            Q[:, j] = Q[:, j] - Q[:, j]*(float(Q[:, j].T*Q[:,i]))
        if la.norm(Q[:, i]) > tol :   #Bewaring to the bias in order to approximate actual result
            Q[:, i] = Q[:, i]/la.norm(Q[:, i])
        else :
            Idx.append(i)
        
    return Q, Idx

In [12]:
A = np.matrix(rn.randn(4, 6))
print(A)

[[-0.66854235 -0.84118087  0.07155467  0.52778347 -1.91091016 -0.11907348]
 [-1.75834401 -0.39528607 -0.32016465 -1.03396213  1.1906435  -0.28794331]
 [ 1.18654415  0.25893903 -0.69680371 -0.08858468  0.73679704 -0.47313373]
 [-0.19657292  0.66799789 -2.01507691  2.15807915  0.34339269 -0.30234834]]


In [13]:
Q, Idx = GS(A)

In [14]:
Q

matrix([[-8.91887165e-02, -1.64300561e+01, -1.01348885e+00,
          4.40959626e-01, -9.87626842e-01, -1.85428646e-01],
        [-2.34576679e-01, -7.72077991e+00,  4.53476057e+00,
         -8.63868582e-01,  6.15367226e-01, -4.48403291e-01],
        [ 1.58294159e-01,  5.05763133e+00,  9.86941556e+00,
         -7.40119215e-02,  3.80803111e-01, -7.36793360e-01],
        [-2.62243468e-02,  1.30474232e+01,  2.85412247e+01,
          1.80306099e+00,  1.77477649e-01, -4.70835694e-01]])

In [15]:
Idx

[]