In [1]:
import numpy as np
import numpy.random as rn
import numpy.linalg as la

In [9]:
#QR decomposition for square matrix

def SQR(A, tol = 10**(-14)) :
    m, n = A.shape
    Q = np.matrix(np.zeros((m, m)))
    R = np.matrix(np.zeros((m, m)))

    for i in range(m) :
        Q[:, i] = A[:, i].copy()
        for j in range(i) :
            R[j, i] = float(Q[:, j].T*Q[:, i])
            Q[:, i] = Q[:, i] -  R[j, i]*Q[:, j]
        if abs(la.norm(Q[:, i])) > tol :
            R[i, i] = la.norm(Q[:, i])
            Q[:, i] = Q[:, i]/R[i, i]

    return Q, R

In [13]:
A = np.matrix(np.round(rn.randn(3, 3)*10))

In [14]:
A

matrix([[-0.,  4., 10.],
        [25., -4., -1.],
        [ 6., -6.,  6.]])

In [26]:
SQR(A)

(matrix([[-0.0696733 , -0.53981136, -0.83889769],
         [-0.90575292,  0.38663526, -0.17356504],
         [-0.41803981, -0.74774118,  0.51587387]]),
 matrix([[14.35270009,  2.85660536, -3.62301167],
         [ 0.        , 14.4512908 ,  1.75413497],
         [ 0.        ,  0.        , 17.05276508]]))

In [24]:
#QR for general matrices

def QR(A, tol=10**-14) :
    m, n = A.shape
    p = min(m, n)

    if m>=n :
        Q = np.matrix(np.zeros((m, n)))
        R = np.matrix(np.zeros((n, n)))
    else :
        Q = np.matrix(np.zeros((m, m)))
        R = np.matrix(np.zeros((m, n)))
    r = 0 #record the rank of A
    i = 0 #record the index of the column

    while r<p and i<n :
        Q[:, r] = A[:, i].copy()
        for j in range(r) :
            R[j, i] = float(Q[:, j].T*A[:, i])
            Q[:, r] = Q[:, r] -  R[j, i]*Q[:, j]
        if abs(la.norm(Q[:, r])) > tol :
            R[r, i] = la.norm(Q[:, r])
            Q[:, r] = Q[:, r]/R[r, i]
            r+=1
        i+=1
    R[:, m:] = Q.T*A[:, m:]

    return Q, R
        


In [21]:
A = np.matrix(np.round(rn.randn(3, 3)*10))

In [22]:
A

matrix([[ -1.,  -8., -15.],
        [-13.,   3.,   1.],
        [ -6., -12.,   9.]])

In [25]:
QR(A)

(matrix([[-0.0696733 , -0.53981136, -0.83889769],
         [-0.90575292,  0.38663526, -0.17356504],
         [-0.41803981, -0.74774118,  0.51587387]]),
 matrix([[14.35270009,  2.85660536, -3.62301167],
         [ 0.        , 14.4512908 ,  1.75413497],
         [ 0.        ,  0.        , 17.05276508]]))